GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "dfgdf",
    "number": "4564"
}
###
POST https://fullstackopen-6h8d.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "ercxvf",
    "number": "5752"
}
###
// Wrong format of id to throw error
GET http://localhost:3001/api/persons/67c5865112b0f277fa96bdf
### 
// Correct format id but no person with that id
GET http://localhost:3001/api/persons/67c56cb7e600885b27460f21
### 
// unknown endpoint
GET http://localhost:3001/api/hej
### 
DELETE http://localhost:3001/api/persons/67c56cb7e6008b27460f21
###
PUT http://localhost:3001/api/persons/67c56e000ee5950b7db803c7 HTTP/1.1
content-type: application/json

{
    "name": "jonas",
    "number": "22"
}