GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "ercxvf",
    "number": "5752"
}
###
POST https://fullstackopen-6h8d.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "ercxvf",
    "number": "5752"
}