GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/67c705bccce08bd00efe171c
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "eld",
  "author": "dfg",
  "url": "www.bdd.com",
  "likes": 323,
  "user_id": "67cac5e905bac8d0696f6eb7"
}
###