GET http://localhost:3001/api/users
###
GET http://localhost:3001/api/users/67cee3516757bcca6dde1075
###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "jonas",
    "password": "1234"
}
###
// Password too short
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "hejhejda",
    "name": "jonasdd",
    "password": "a"
}
###
// Username too short
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "h",
    "name": "jonasdd",
    "password": "afghfg3"
}
###
DELETE http://localhost:3001/api/users/67cee3516757bcca6dde1075